# -*- coding: utf-8 -*-
"""retrieve_timestamp.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AKzrzlG5AZN8W2lk4i7_YC-Olfklr8xM
"""

from google.colab import drive
drive.mount('/content/gdrive')



!cp "gdrive/My Drive/graphs_covid.zip" .
!unzip graphs_covid.zip

import pandas as pd
from glob import glob

images = glob("graphs_covid/*")
images[1].split('/')[1]

len(images)

!cp "gdrive/My Drive/merged.csv" .

from tqdm import tqdm

data = pd.read_csv('merged.csv')

!cp -R "gdrive/My Drive/new" .

columns = list(data.columns)
new_data = pd.DataFrame(columns=columns)
new_data

timestamp = []
id = []
count = 0
for image in tqdm(images):
  name = image.split('/')[1]
  vertex = name.split('#')[0]
  imported = int(name.split('#')[1])
  row = data[(data['Vertex 1'] == vertex)]
  if not row.empty:
    count += 1
    boo = True
    for ind, r in row.iterrows():
      #imp_id = r['Imported ID']
      #imp_id = str('{:.8f}'.format(float(imp_id)))[:16]
      temp = str(r['Imported ID']).split('e')[0]
      imp_id = temp.split('.')[0] + temp.split('.')[1]
      if imp_id[:len(imp_id)-2] == str(imported)[:len(imp_id)-2] or r['Imported ID'] == imported:
        #timestamp.append((name, r['Tweet Date (UTC)']))
        #images.remove(image)
        new_data = new_data.append(r)
        boo = False
        break
    if boo:
      id.append(image)
      
print(count)

new_data.to_csv('image_data.csv')

cur = data[(data['Vertex 1'] == 'stabilitasv')]
print(id[246])
for _,row in cur.iterrows():
  print(row['Imported ID'])

temp = cur.iloc[1]['Imported ID']
imp_id = str('{:.8f}'.format(float(temp)))[:16]
nu = 1247162731507171328
imp_id == str(nu)[:16]
temp = str(temp).split('e')[0]
temp = temp.split('.')[0] + temp.split('.')[1]
temp == str(nu)[:len(temp)]

df = pd.DataFrame(timestamp, columns=['name', 'time'])

df.to_csv('timestamp.csv')

!cp timestamp.csv "gdrive/My Drive/"

image_list = []
for image in images:


  image_list.append(image.split('/')[1].split('#')[0] + '#' + image.split('/')[1].split('#')[1])
image_list
sum = 0
for image in image_list:
  sum += len(image.split('#')[1])
print(sum/len(image_list))

data.iloc[234215]['Imported ID']

image_list[1]
row = data[(data['Vertex 1'] == 'shaolintom')]
row

print(row.iloc[2]['Imported ID'])
#(data['Imported ID'] == 1243184941661409280)
for ind, r in row.iterrows():
  imp_id = r['Imported ID']
  imp_id = str('{:.8f}'.format(float(imp_id)))[:16]
  print(imp_id == str(1243184941661409280)[:16])

from decimal import *
input = 1.243184941661409e+18
print('{:.8f}'.format(float(input)))
print(16)

1.243184941661409e+18 == 1243184941661409280

dic = {}
arr = [1,2,3,2,4,4,4,5,11,1,0]
for num in image_list:
  dic[num] = dic.get(num,0) + 1

boo = True
for key in dic:
  if dic[key] > 1:
    boo = False
print(boo)

